blivetgui/blivet_utils.py
blivetgui/dialogs/add_dialog.py
blivetgui/dialogs/edit_dialog.py
blivetgui/dialogs/helpers.py

Allow "none" as format when adding/editting devices

---

blivetgui/blivetgui.py

Add progress dialog for storage reload

---

blivetgui/blivetgui.py
blivetgui/dialogs/message_dialogs.py
blivetgui/list_actions.py
blivetgui/osinstall.py

Changes related to showing pending actions in installer mode.

Fix showing actions in installer mode

---

blivet-gui.spec
blivetgui/blivet_utils.py
blivetgui/blivetgui.py
blivetgui/dialogs/add_dialog.py
blivetgui/dialogs/edit_dialog.py
blivetgui/dialogs/helpers.py
blivetgui/dialogs/message_dialogs.py
blivetgui/list_actions.py
blivetgui/list_partitions.py
blivetgui/osinstall.py
data/ui/blivet-gui.ui
data/ui/exception_dialog.ui
data/ui/format_dialog.ui
data/ui/mountpoint_dialog.ui
data/ui/resize_dialog.ui
data/ui/size_area.ui
tests/blivetgui_tests/add_dialog_test.py
tests/blivetgui_tests/edit_dialog_test.py

Mostly small UI changes and bug fixes.

Few more installer mode related changes

---

blivetgui/blivetgui.py
blivetgui/list_actions.py
data/css/rectangle.css
data/ui/blivet-gui.ui
tests/blivetgui_tests/list_actions_test.py

Gtk.Label with URI doesn't work when embedded in Anaconda

Use Gtk.Button for showing number of scheduled actions

---

blivetgui/dialogs/add_dialog.py
blivetgui/list_partitions.py

Fixing two bugs found by @M4rtinK when testing blivet-gui in Anaconda.

Two installer related fixes

---

blivetgui/processing_window.py
po/blivet-gui.pot

Typo/spelling fix: corrected "proccesing" to "processing"

Spelling: corrected "proccessing" to "processing"

---

blivetgui/config.py
blivetgui/dialogs/add_dialog.py
blivetgui/dialogs/edit_dialog.py
blivetgui/dialogs/helpers.py
blivetgui/dialogs/other_dialogs.py
blivetgui/list_partitions.py
data/ui/blivet-gui.ui
data/ui/raid_chooser.ui
tests/blivetgui_tests/edit_dialog_test.py

Fixes for few bugs found during blivet-gui Anaconda test day.
Updates image to test this (including some Anaconda changes): https://vtrefny.fedorapeople.org/img/bg-td.img

Few fixes for Anaconda

---

blivetgui/blivet_utils.py
blivetgui/blivetgui.py
blivetgui/dialogs/add_dialog.py
blivetgui/dialogs/message_dialogs.py
blivetgui/dialogs/size_chooser.py
blivetgui/list_partitions.py
blivetgui/processing_window.py
data/ui/confirm_delete_dialog.ui
tests/blivetgui_tests/add_dialog_test.py
tests/blivetgui_tests/size_widgets_test.py

Third batch of fixes for bugs found during blivet-gui in Anaconda test day.

Few more fixes for Anaconda

---

blivetgui/osinstall.py

Do not use Gtk.Widget.reparent it is deprecated since 3.14

---

blivetgui/list_devices.py
blivetgui/list_partitions.py
blivetgui/osinstall.py
blivetgui/visualization/logical_view.py
data/ui/blivet-gui.ui
data/ui/size_chooser.ui

Few more fixes related to blivet-gui in Anaconda.

More installer related fixes

---

blivetgui/dialogs/size_chooser.py
tests/pylint/runpylint.py

New pylint, new false positives.

Ignore pylint error "not-context-manager" for locks

---

blivet-gui.spec

Require "PolicyKit-authentication-agent" instead of "polkit-gnome"

---

blivet-gui-daemon
blivet-gui_event.conf
blivetgui/blivet_utils.py
blivetgui/config.py
blivetgui/logs.py
blivetgui/osinstall.py

Log example: https://vtrefny.fedorapeople.org/misc/blivet-gui-utils.log

BlivetUtils logs

---

Makefile
blivetgui/blivet_utils.py
tests/blivetutils_tests/blivetutilstestcase.py
tests/blivetutils_tests/targetcli_config.json
tests/blivetutils_tests/test_10_disks.py
tests/blivetutils_tests/test_20_partitioning.py

Test suite for `BlivetUtils` class.

Add tests for BlivetUtils class

---

blivetgui/blivet_utils.py

This is just a quick for the bug. Better solution and probably removing of the whole `RawFormatDevice` class should follow.

Fix opening raw LUKS format (#1519049)

---

blivetgui/dialogs/add_dialog.py
tests/blivetgui_tests/add_dialog_test.py

We don't want to allow creating >2 TiB partitions on msdos disks.

Limit partition max size based on disklabel limits (#1623659)

---

Makefile
install-test-dependencies.yml

The tool has been renamed two years ago -- https://github.com/PyCQA/pycodestyle/issues/466

Use 'pycodestyle' instead of 'pep8'

---

blivetgui/blivet_utils.py

We want to display the LUKS device not the Integrity device which
is not directly usable by the user.

Correctly display LUKS with integrity (#1729888)

---

blivetgui/blivet_utils.py

It was depracated for few releases and finally removed in 3.8.

Remove platform.linux_distribution

---

README.md

README: Add information about Debian and Ubuntu repository.

---

blivetgui/actions_menu.py
blivetgui/actions_toolbar.py
blivetgui/blivet_utils.py
blivetgui/blivetgui.py
blivetgui/dialogs/edit_dialog.py
blivetgui/list_partitions.py
data/ui/blivet-gui.ui
data/ui/label_dialog.ui

This was originally implemented and merged more than 3 years ago (see #26) but for some reason the code is not on master. There is no revert commit so it was probably lost in some branch rebase (but I have no idea how).

Add support for changing filesystem label

---

.gitignore
Makefile
po/bg.po
po/ca.po
po/cs.po
po/de.po
po/es.po
po/fi.po
po/fr.po
po/fur.po
po/he.po
po/hu.po
po/it.po
po/ja.po
po/kk.po
po/pa.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sk.po
po/sq.po
po/sr.po
po/uk.po
po/zh_CN.po
po/zh_TW.po
zanata.xml

Preparations for migration to Weblate

---

blivetgui/blivet_utils.py
blivetgui/blivetgui.py
blivetgui/communication/client.py
blivetgui/communication/server.py
blivetgui/dialogs/edit_dialog.py
blivetgui/list_partitions.py
data/css/rectangle.css
data/ui/unmount_dialog.ui
po/blivet-gui.pot
tests/blivetgui_tests/list_partitions_test.py
tests/blivetgui_tests/server_test.py

This takes care of both displaying and unmounting devices that are mounted at multiple locations.

Multiple mountpoints in the UI

---

blivetgui/dialogs/add_dialog.py

Only msdos partition table supports extended partitions.

Do not allow creating extedned partitions on DASD (#1825357)

---

blivetgui/blivet_utils.py

Correctly set data and metadata level when creating Btrfs volumes

---

blivetgui/blivet_utils.py

The past tense of "choose" is "chose" not "choosed".

The past tense of "choose" is "chose"

---

blivetgui/blivet_utils.py

Do not try to check parent device type for devices without parents

---

blivetgui/osinstall.py

Fix missing attribute _resizable_filesystems in BlivetUtilsAnaconda

---

blivetgui/blivet_utils.py

Follow-up for #221, disks needs some special treatment in this
case.

Fix displaying disks with unknown formats

---

blivetgui/blivet_utils.py
blivetgui/blivetgui.py
blivetgui/dialogs/message_dialogs.py
blivetgui/list_partitions.py
data/ui/confirm_delete_dialog.ui
tests/blivetgui_tests/list_partitions_test.py

This will allow easily remove entire VG including all LVs in one
action.

Allow removing devices with children

---

blivet-gui
blivetgui/blivetgui.py
man/blivet-gui.1

Actually a very simple to implement, because I already have all the parts in the `BlivetUtils` code to limit disks used for tests. The "frontend" part is very simple.

Allow specifying exclusive disks when running blivet-gui

---

blivetgui/blivet_utils.py

We need to wipe the mdmember format from the parent devices,
removing the array itself is a no-op in blivet.

Fix removing existing MD arrays

---

blivetgui/blivet_utils.py
blivetgui/communication/client.py
blivetgui/visualization/logical_view.py
tests/blivetgui_tests/utils_test.py

Dead code, unused variables etc.

Fix various alerts found by LGTM

---

blivet-gui.spec
blivetgui/blivet_utils.py
blivetgui/dialogs/add_dialog.py
blivetgui/dialogs/widgets.py
data/ui/encryption_chooser.ui
po/blivet-gui.pot
tests/blivetgui_tests/add_dialog_test.py
tests/blivetgui_tests/widgets_test.py

Encryption sector size selection support

---

blivetgui/blivet_utils.py
blivetgui/blivetgui.py

Add function to log to the utils log from the GUI process

---

blivet-gui.spec

https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1

spec: Change license string to the SPDX format required by Fedora

---

blivetgui/dialogs/add_dialog.py
blivetgui/list_partitions.py
tests/blivetgui_tests/list_partitions_test.py

Allow adding nested btrfs subvolumes

---

blivetgui/list_devices.py

Fix segfault when trying to reuse an invalid GtkTreeIter

---

blivet-gui
blivetgui/blivet_utils.py
blivetgui/blivetgui.py
man/blivet-gui.1

Add a cmdline option to enabled blivet's auto_dev_updates flag

---

blivetgui/blivetgui.py

We want to log the action only when the mount point change is actually confirmend not every time.

Fix logging for mount point change

---

.github/workflows/check.yml
misc/Vagrantfile
misc/install-test-dependencies.yml

Mostly related to testing https://github.com/storaged-project/blivet/pull/1204 with the latest Ubuntu 24.04 (pre-release).

Misc updates for the test dependencies playbook

---

blivetgui/blivet_utils.py
blivetgui/list_devices.py

Fix pylint 'possibly-used-before-assignment' warnings

---

blivet-gui.spec
blivetgui/blivet_utils.py
tests/blivetgui_tests/utils_test.py

Add support for filesystem online resize

---

README.md
blivetgui/blivetgui.py
blivetgui/dialogs/device_info_dialog.py

Show all mountpoints in device info dialog

---

blivetgui/dialogs/message_dialogs.py
data/ui/exception_dialog.ui
po/blivet-gui.pot

The "Report a bug" button which uses ABRT to report bugs may not work everytime so let's just add a short explanation what the button does and link to GH issues for people that want to report a bug manually.
Related: #445

Add label explaining bug reporting using ABRT and link to GitHub
