storaged-project/blivet-gui

blivetgui/blivet_utils.py, blivetgui/dialogs/add_dialog.py, blivetgui/dialogs/edit_dialog.py, blivetgui/dialogs/helpers.py, data/ui/format_dialog.ui, tests/blivetgui_tests/add_dialog_test.py
Remove special "type" for adding lvmpv and allow using lvmpv as a format for all devices.
Same applies for btrfs, but "btrfs volume" can be still added to allow adding btrfs volume with multiple (non-existing) parents.
=> Allow using btrfs and lvmpv as format for all devices

Makefile
There are some problems with running Gtk applications using xvfb, this should probably fix this.
=> Fix floating point exception when running test using xvfb-run

blivetgui/blivetgui.py, blivetgui/dialogs/constants.py, blivetgui/dialogs/message_dialogs.py, blivetgui/exception_handler.py, blivetgui/gui_utils.py, data/ui/exception_dialog.ui
With recent remove of python-meh support, blivet-gui needs some
basic exception handler that would show the error and quit the
GUI. System exception handler (ABRT) is restored for automatic
reporting.
=> Add custom exception handler for blivet-gui

blivetgui/actions_menu.py, blivetgui/actions_toolbar.py, blivetgui/blivetgui.py, blivetgui/dialogs/edit_dialog.py, blivetgui/list_partitions.py, data/ui/blivet-gui.ui, data/ui/format_dialog.ui, data/ui/mountpoint_dialog.ui, tests/blivetgui_tests/add_dialog_test.py, tests/blivetgui_tests/edit_dialog_test.py
Add support for setting mountpoints in installer mode both with and without reformatting the device.
Third commit (_Use Gtk.Window in AddDialogTest instead of Mock_) is not related to this. I just realized this could be done in a better way when writing test for the `FormatDialog`.
=> Add support for setting mountpoints

blivetgui/blivet_utils.py, blivetgui/blivetgui.py, blivetgui/dialogs/add_dialog.py, blivetgui/dialogs/size_chooser.py, blivetgui/dialogs/widgets.py, data/ui/raid_chooser.ui, tests/blivetgui_tests/add_dialog_test.py, tests/blivetgui_tests/size_widgets_test.py, tests/blivetgui_tests/widgets_test.py
There are two major changes in this PR:
- Changes related to size selection in AddDialog -- reworked SizeArea (now with tests!)
- Removing of support for LVM RAID and LVM cache -- these will be just temporary, but there is a lot of problems with allocating multiple LVs and having these features disabled will help with testing the blivet-gui integration to Anaconda
=> AddDialog and SizeArea changes

blivetgui/blivetgui.py, blivetgui/osinstall.py
This is needed for installer mode. Simply watching changes of
actions isn't enough, because there are some changes that doesn't
have actions (e.g. chaning mountpoint).
=> Add a special method for handling changes made by user

blivetgui/dialogs/add_dialog.py
'free' is not updated after removing LVs
Resolves: rhbz#1429988
=> AddDialog: Use 'free_space' instead of 'free' for VGs free space

blivetgui/dialogs/edit_dialog.py
When changing format and setting mountpoint for the new format,
do not automatically check for previous mountpoint (old format
may not be mountable).
=> Do not try to check mountpoint for unmountable formats (#1439108)

blivetgui/blivet_utils.py, blivetgui/blivetgui.py, blivetgui/dialogs/add_dialog.py, blivetgui/dialogs/size_chooser.py, tests/blivetgui_tests/add_dialog_test.py, tests/blivetgui_tests/size_widgets_test.py
Blivet allows specifying "weight" when adding a partition. Heavier
partitions are added first. Without setting proper weight when
adding a partition in blivet-gui, partitions are actually added
in reverse order.
=> Preserve ordering when adding partitions (#1439591)

blivet-gui.spec
pygobject3 is actually a python2 library (provided by python-gobject) where
the rest of blivet-gui depends on python3 so the dep should be python3-gobject
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
=> Use python3-gobject not pygobject3

blivetgui/dialogs/add_dialog.py
Because iSCSI disks have type "iscsi" not "disk".
=> Use "is_disk" to check if device is disk (#1457163)

data/css/rectangle.css, data/ui/blivet-gui.ui
It might be hard for people to notice that the buttons for
adding/deleting/editting seleted device are actually buttons.
This change will make the toolbar look more like a toolbar.
---
Screenshot of new version -- https://vtrefny.fedorapeople.org/blivet-gui/bg-toolbar.png
=> Make the device toolbar look more "toolbarish" (#1456011)

blivetgui/blivet_utils.py
We need to save the passpharase so Anaconda can open the LUKS
device again.
=> Fix reusing LUKS devices in Anaconda (#1462071)

blivet-gui.spec
Anaconda now depends on blivet-gui, but Fedora Workstation group
doesn't want blivet-gui to be on the installed system. And because
Anaconda can't remove packages after installing from a LiveCD, we
need to split blivet-gui package into a "-runtime" package that
contains all the code and "blivet-gui" package that contains
only the desktop file and appdata (and depends on the "-runtime"
package).
Resolves: rhbz#1449752
=> Split blivet-gui package into "blivet-gui" and "blivet-gui-runtime"

blivet-gui_event.conf
We can't use "pkg_name" because of splitting the package into
"blivet-gui" and "blivet-gui-runtime".
=> Fix ABRT/libreport config for blivet-gui

blivetgui/dialogs/edit_dialog.py
Resize option shouldn't be available for non-resizable devices
but if it is available (it sometimes might happen), ResizeDialog
shouldn't crash.
=> Fix displaying resize dialog for non-resizable devices (#1473350)

blivetgui/blivet_utils.py
We do not want to call teardown when scheduling the destroy action,
there may still be some active/existing children scheduled for
destroying and running "luksClose" will fail because of that.
Blivet also calls teardown() in _pre_destroy so this definitely
isn't needed.
=> Do not try to teardown luks devices before removing (#1466940)

blivetgui/dialogs/add_dialog.py, tests/blivetgui_tests/add_dialog_test.py
Use "DeviceFormat.labeling" method to check if selected filesystem
supports labels.
=> AddDialog: Fix displaying filesystem label entry

blivetgui/actions_menu.py, blivetgui/actions_toolbar.py, blivetgui/blivetgui.py, blivetgui/list_partitions.py, data/ui/blivet-gui.ui
This adds a new option to the "edit" menu. It uses the same
dialog as adding a new disklabel to an unitialized disk.
=> Allow changing partition table (disklabel)

blivetgui/blivet_utils.py, blivetgui/blivetgui.py, blivetgui/dialogs/add_dialog.py, blivetgui/dialogs/edit_dialog.py, blivetgui/dialogs/helpers.py, tests/blivetgui_tests/add_dialog_test.py, tests/blivetgui_tests/edit_dialog_test.py
A filesystem is "supported" only if we find tools to create it
in PATH but on some systems (e.g. Debian) /usr/sbin is not in PATH
for users so we need to obtain the list of supported filesystems
in the root process.
=> Get supported filesystems in the 'backend' process

blivetgui/blivet_utils.py
Since blivet commit 6a9f746a, this method doesn't accept a
'hostname' kwarg any more, so we can't pass one. This caused
any attempt to create some kind of container (VG, software
RAID set, etc) using blivet-gui to trigger a crash.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Don't pass 'hostname' kwarg to suggest_container_name (#1528103)

blivetgui/dialogs/edit_dialog.py
In FormatDialog check also maximal size of the filesystem before
allowing to use it. E.g. don't offer biosboot for devices bigger
than 2 MiB.
=> Do not allow to format large devices to biosboot (#1532253)

blivetgui/osinstall.py
BlivetGUIAnaconda subclasses BlivetGUI, but doesn't call the
parent class's __init__. c4b6e174 added supported_filesystems
to BlivetGUI and set _supported_filesystems for caching during
__init__, but this was not also added to BlivetGUIAnaconda, so
when anything tries to use the supported_filesystems property
of a BlivetGUIAnaconda instance, it will crash. This is causing
all attempts to use blivet-gui in anaconda to crash since 2.1.8
landed in Rawhide.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Set _supported_filesystems in BlivetGUIAnaconda init

data/ui/about_dialog.ui
Looks less outdated without one than with the wrong one, and it’s one less place to remember to update the copyright year.
=> [trivial] Removed copyright year from About dialog

blivetgui/blivetgui.py, blivetgui/list_actions.py, blivetgui/list_devices.py, blivetgui/osinstall.py, blivetgui/processing_window.py
Pylint thinks that some Gtk functions that doesn't expect any
parameters actually need a "self" parameter.
=> Ignore pylint 'no-value-for-parameter' warning

Makefile
PEP8 has changed and it now requires line breaks before a binary
operator instead after: https://hg.python.org/peps/rev/3857909d7956
Unfortunately older versions of pep8 still report it as warning
(W503) and we don't have a simple way how to ignore different
warnings based on pep8 version.
=> Ignore PEP8 W504 warning ("line break after binary operator")

blivetgui/blivet_utils.py
In blivet MD arrays are disks, but we have a special category in
the UI, so we need to remove it here.
=> Do not show MD arrays in disks section

blivetgui/blivet_utils.py
'suggest_device_name' with 'parent' specified works only for LVM,
because LVM names are combination of VG name and LV name. For
btrfs subvolumes this results in a non-unique name recommendation.
=> Fix suggesting names for btrfs subvolumes (#1648631)

blivetgui/blivet_utils.py
This must be a list, not a generator, because we are iterating
over it multiple times in some cases.
=> Fix return type of BlivetUtils.get_disks (#1658893)

blivetgui/blivet_utils.py, blivetgui/list_partitions.py
This is better solution for btrfs mountpoint problem originally
fixed in 402ef7d1165d6a609267b107b8fe6a503ec5ee0d
=> Use 'direct' device property to (dis)allow mountpoint selection

blivetgui/dialogs/add_dialog.py
We still need to check min size limit for the device we are
creating to be sure to include the filesystem/format minimal size.
E.g. we need to set 10 MiB for lvmpv (2 MiB for LUKS metadata +
8 MiB for PV metadata).
This was discovered thanks to recent changes in blivet -- all
filesystems now have non-zero minimal size.
=> Count format minimal size when checking encrypted device min size

blivetgui/blivet_utils.py, blivetgui/dialogs/device_info_dialog.py, blivetgui/list_partitions.py
These are devices created using integritysetup, so just "plain"
integrity device without encryption.
=> Propertly display standalone dm-integrity devices

tests/pylint/runpylint.py
Unfortunately pylint still doesn't understand the new positional
only arguments syntax from Python 3.8 (PEP 570) and because Mock
is already using these pylint is failing on 3.8.
Also remove some old false positives that are no longer valid.
=> Mark E1121 pylint error as false positive in tests

blivetgui/blivet_utils.py
False is default but not setting this explicitly makes pylint
unhappy (W1510 subprocess-run-check).
=> Explicitly disable return code check in subprocess.run

blivetgui/blivet_utils.py, tests/blivetutils_tests/blivetutilstestcase.py, tests/blivetutils_tests/test_20_partitioning.py
Sorting using weight unfortunately works only for non-existing
partitions and breaks if there is a preexisting partition in the
middle of the disk. The best way to be sure the partition is
always created in the correct free region selected from the GUI
seems to be specifying starting sector for each partition.
We also need to make sure the starting sector is correctly aligned
because blivet doesn't align partitions with the start sector set.
The alignment code is inspired by the `bd_part_create_part`
function from libblockdev and alignment code there.
=> Specify starting sector when creating partitions (#1755813)

MANIFEST.in
This is need to run tests in build environemnts, for example in
Fedora CI.
=> Add tests to the source archive

blivetgui/blivet_utils.py, blivetgui/dialogs/add_dialog.py, blivetgui/dialogs/helpers.py, blivetgui/dialogs/size_chooser.py, blivetgui/dialogs/widgets.py, data/ui/encryption_chooser.ui, tests/blivetgui_tests/add_dialog_test.py, tests/blivetgui_tests/widgets_test.py
Blivet now supports both LUKS1 and LUKS2 so we should allow
choosing the "type" of encryption which will be used.
All "encryption" widgets from AddDialog were also moved to a new
EncryptionChooser widget.
=> Allow selection of encryption type (LUKS version)

blivetgui/blivet_utils.py, blivetgui/blivetgui.py, blivetgui/osinstall.py
Anaconda originally did this in the blivet-gui spoke but we need
to move all code that works with the Blivet instance to blivet-gui.
Fixes #139
=> Get default filesystem type from blivet

blivetgui/blivetgui.py, blivetgui/dialogs/message_dialogs.py, blivetgui/osinstall.py
We need to make sure it's set to be always above the displayed
dialog and also to remove window decoration when running in the
installer environment.
=> Fix displaying the exception dialog in Anaconda

Makefile, tests/blivetgui_tests/add_dialog_test.py, tests/blivetgui_tests/edit_dialog_test.py, tests/blivetutils_tests/test_10_disks.py, tests/blivetutils_tests/test_20_partitioning.py, tests/run_tests.py
This also allows running the test suite against the installed
version of blivet-gui, for example in the Fedora CI.
=> Add a simple script to run tests

blivetgui/dialogs/edit_dialog.py
Blivet enforces strict alignment constraints when resizing devices
and it is possible to have a device (unaligned partition usually)
that is bigger (or smaller) than max (min) size calculated by
blivet. For these devices we can't set the current size in the
resize dialog so just set the max (min) size instead, it shouldn't
be more than few KiBs different.
=> Fix displaying current size of devices in the resize dialog

.packit.yaml
F29 is EOL and Copr chroots for it have been removed.
=> Update packit Copr targets

.packit.yaml
This should automatically build on all available versions of
Fedora.
=> packit: Use 'fedora-all' as Copr build targets

blivetgui/communication/client.py, blivetgui/communication/server.py, tests/blivetgui_tests/server_test.py
This fixes bug with setting mountpoint in the installer mode.
Setting attributes used to work with older versions of Python
without overriding the "__setattr__" method on proxy objects.
=> Fix setting attributes for proxy objects (#1810855)

blivetgui/blivet_utils.py
We are creating a "fake" user input for the PVs creation so the
correct keyword is "encryption_type" not "luks_version" which is
used by blivet "get_format".
=> Fix creating encrypted LVM VG (#1816098)

blivetgui/blivet_utils.py, blivetgui/osinstall.py
When running in Anaconda composite devices like RAIDs are teared
down so we need to run setup() on the device before trying to
unlockit it.
=> Fix unlocking LUKS on RAID in the installer mode (#1787508)

blivetgui/blivet_utils.py
Blivet runs update_size_info automatically in Anaconda so we don't
need to do it again. Also our update_size_info call will always
fail for LVs because they are no longer active when blivet-gui is
running (because anaconda runs teardown_all during populate).
Resolves: rhbz#1826370
=> Do not update filesystem info for resize in the installer mode

blivetgui/dialogs/device_info_dialog.py
New plyint doesn't like underscores in warning IDs.
(found-_-in-module-class is a custom warning added by pocketlint.)
=> Fix pylint failure when disabling found-_-in-module-class warning

data/ui/blivet-gui.ui
To match the edit button menu.
Fixes: #176
=> Fix ordering of the edit submenu in the context menu for devices

blivetgui/list_partitions.py, data/ui/blivet-gui.ui, tests/blivetgui_tests/list_partitions_test.py
The fedora install defaults the volume group to be named "fedora_hostname" and because the device list prefixes the logical volumes with this I was unable to see the names of most of my logical volumnes as they were truncated after 15 characters and wouldn't display even if I resized the column. 
I switched from the hard coded truncation to letting the GTK cell render truncate based on the column width as it allows the user to see longer names if they resize the column.
The "fixed width" of 110 comes from looking at the old UI and how wide the column was with the existing 18 character max length (15 + three ellipses)
=> Ellipse the device name using the GTK cell render

blivetgui/blivet_utils.py, blivetgui/dialogs/edit_dialog.py, blivetgui/list_partitions.py, tests/blivetgui_tests/utils_test.py
We currently decide if the device is resizable completely in the
GUI using the "_allow_resize_device" function which makes some of
the devices not resizable even if they can be resized. To properly
decide we usually need to call "update_size_info" on the format
first.
This change moves the decision to the backend (except for devices
that clearly can't be resized, like protected or unsupported
devices) and shows the reason for the device not being resizable
in the resize dialog.
Fixes: #175
=> Refactor checking for device resizability

blivetgui/blivet_utils.py
We now call setup() on encrypted devices prior to trying to unlock
them in the installer mode to fix issues with devices stopped or
deactivated during the installation environment setup, see
56d97b3b7dead7a80fc9d50bcd373e8390843cd8 but this doesn't work for
devices represented by the RawFormatDevice class in blivet-gui so
we need to propage the setup() call to the underlying disk.
----
I really need to remove the `RawFormatDevice` "device". It orignally looked like a great way to visualize raw format disks, but it only causes more and more issues right now.
=> Fix unlocking raw format LUKS devices in Anaconda (#1846517)

blivet-gui.spec
It's not really needed, any theme with the "symbolic" icons will
do and since dba6d24962428992dacf3430225e206dc6eb4cf1 blivet-gui
will no longer crash when trying to load non-existing icons.
=> Remove dependency on adwaita-icon-theme

blivetgui/dialogs/edit_dialog.py
Currently is possible -> Currently it it's possible
Can also be it is if it sounds better.
=> Grammar fix

blivetgui/dialogs/widgets.py
Visibility of the "advanced" fields of the encrypt widget (type and
passphrase) always depends on the encrypt checkbox status even if
we force it to be displayed.
=> Fix setting visibility for EncryptionChooser

blivetgui/gui_utils.py, setup.py
Installation from repositories (where possible) is still preferred, but this should make manual installation using pip a little bit more user-friendly.
=> Pip friendly installation

blivetgui/blivet_utils.py, blivetgui/list_parents.py
Blivet is going to remove the slave property from LUKS (and other)
device object: https://github.com/storaged-project/blivet/pull/863.
=> Use "raw_device" instead of "slave" for getting LUKS backing device

blivetgui/blivet_utils.py, blivetgui/blivetgui.py, tests/blivetgui_tests/utils_test.py
Blivet uses the "_resizable" parameter for both indicating that
the filesystem is not resizable and that we don't have enough
information to tell (e.g. running "update_size_info" is needed
firsts) so we need to gather the information from the class object
instead from the filesystem instance.
=> Gather resizable filesystems from blivet instead of hardcoding

blivetgui/blivet_utils.py
We validate names in GUI so there is no need to replace the name
with a "safe" one.
=> Do not force "safe" names for devices (#1859963)

blivetgui/blivetgui.py, blivetgui/visualization/rectangle.py, data/ui/luks_passphrase_dialog.ui
"Decrypt" is completely wrong here and open/close can be confusing
so lets use "lock" and "unlock" in user-visible strings.
=> Unify/fix terminology for (un)locking encrypted devices

tests/blivetgui_tests/add_dialog_test.py
For this test we don't really need to check for system support of
the filesystem, we just need a "stable" list of filesystems to
check. Also some of the formats (like LVMPV) are not "supported"
when running as a non-root user.
=> Hardcode list of supported filesystems for AddDialog tests

blivet-gui.spec
blivet-gui-runtime doesn't need it and it can pull in "weird"
implementations of polkit like lxpolkit on Workstations.
See https://pagure.io/fedora-workstation/issue/180 for details.
=> Move the PolicyKit agent dependency from runtime to blivet-gui

blivetgui/blivet_utils.py
This is not ideal, but we can't use the "is_disk" property from
blivet because it is True also for RAID arrays.
=> Handle sector mode NVDIMMs as disks

blivet-gui.spec
We should be in theory able to run without some specific plugins
but it can be confusing especially with recent changes to installer
and blivet dependencies and it's easier to just require all
plugins in the blivet-gui package.
=> spec: Require all libblockdev plugins

blivet-gui.spec
make is no longer part of the default build environment in Fedora.
=> Add make to build dependencies

blivetgui/blivet_utils.py, blivetgui/communication/proxy_utils.py, blivetgui/dialogs/add_dialog.py, tests/blivetgui_tests/add_dialog_test.py
Similar change to https://github.com/storaged-project/blivet/pull/969 This makes sure the "advanced options" tab which allows setting chunk size for MD RAID is hidden and we don't set the default value when creating `MDRaidArrayDevice`.
=> Do not allow setting chunk size for RAID 1 (#1996223)

setup.py
The distutils module is deprecated and will be removed in Python
3.12.
=> Use setuptools instead of distutils in setup.py

blivetgui/blivet_utils.py
We can't run format.teardown() for formats that have not been
created yet.
Resolves: rhbz#2005289
=> Fix DeviceFormatError when removing a non-existing MD array

blivetgui/blivet_utils.py
When removing a device with its parents (e.g. VG and PVs together)
we need to remove not only the LUKS container but also the
underlying block device so we must use the full "delete_device"
function which takes care of this.
=> Fix removing encrypted parents

data/ui/blivet-gui.ui
In some cases (especially when the device names or mountpoints are
too long) the logical view can "overflow" and cause the main menu
buttons to move "outside" the window. Adding a scrolled windows
prevents this.
Fixes: #311
=> ui: Add Gtk.ScrolledWindow as parent for the logical Gtk.TreeView

data/ui/label_dialog.ui
Copy-paste bug from the format dialog, the title originally said
"Format device" instead of "Set filesystem label".
=> Fix title for the label dialog

blivet-gui.spec
polkit package provides "pkexec" which we use for starting the
privileged background process.
=> spec: Add explicit dependency on polkit

blivetgui/list_actions.py, blivetgui/processing_window.py
adwaita-icon-theme 42 no longer includes the non-symbolic icons
for these names. The choices are to switch to symbolic ones or
carry the non-symbolic ones downstream.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Use symbolic list-add and edit- icons (Adwaita dropped old ones)

blivet-gui.spec
gettext is needed only during build time.
=> spec: Remove dependecy on gettext

blivet-gui-daemon, blivetgui/communication/server.py, tests/pylint/runpylint.py
Latest pylint removed some deprecated warnings/messages and now
complains about disabling unknown messages.
=> pylint: Remove deprecated pylint warnings from pylintrc and code

misc/install-test-dependencies.yml
We using mock from unittest, no need for python3-mock.
=> Remove python3-mock from test dependencies

blivetgui/list_devices.py
We were using the "drive-multidisk" icon, but that's no longer
available in the default GNOME Adwaita theme (only as the symbolic
icon) so we need a new icon to make the look consistent. Folder
isn't the best, but there isn't a more fitting option.
=> Use "folder" icon for LVM and other "complex" devices

blivetgui/blivet_utils.py
zRAM devices are not scanned by udev so we see them as empty so
it's better to just not show them to not confuse users especially
because there is now a zRAM devices on every Fedora system used
for swap.
=> Tell blivet to ignore zRAM devices

blivetgui/blivet_utils.py, blivetgui/blivetgui.py, tests/blivetgui_tests/add_dialog_test.py
With the new Anaconda WebUI more users are going to watn to create storage layout before starting the installation and we need to support creating biosboot in these cases.
=> Allow creating biosboot even if not in installer mode

tests/pylint/censorship.py
The 'do_exit' keyword argument has been deprecated for a while and finally removed in pylinr 3.0.
=> pylint: Use 'exit' instead of 'do_exit' for pylint.lint.Run

blivetgui/dialogs/edit_dialog.py
The dialog can be closed with a different action than REJECT (like DELETE_EVENT when closing the dialog with Esc) so we need to explicitly check for the ACCEPT response instead the other way around.
Resolves: rhbz#2241761
=> Fix logic when checking for dialog response

blivetgui/dialogs/helpers.py
Next version of Blivet is going to remove support for JFS and ReiserFS.
=> Remove support for labelling JFS and ReiserFS

blivet-gui.spec
The daily builds from Packit are now behind because the automatic rebuilds in Fedora have higher release.
=> spec: Bump release to 99 to be always ahead of the Fedora packages

.packit.yaml, blivet-gui.spec
We want a high release number (99) for the daily builds done by Packit to make sure the Copr daily builds are always newer than the version in Fedora. We can do this in Packit config instead of bumping the release in the spec everytime.
=> ci: Set custom release suffix for Packit

.packit.yaml
Specifying "actions" for a job overrides all the global actions so we need to specify all actions again, not just add a new "post-upstream-clone" action for the job.
=> ci: Fix Packit actions to bump release number

blivetgui/dialogs/add_dialog.py
This happens more often since blivet dropped linear from mdraid in https://github.com/storaged-project/blivet/pull/1236 . It was the only RAID level supported for mdraid that had min_members of 1. When you add the first member for a new mdraid set, of course, there is only one member.
RaidChooser's update method checks the `min_members` on each level and only adds it to the liststore of available levels if we currently have at least that many members. So, before that blivet change, when there was only one member, "linear" was the only level in the liststore, and was necessarily the selected_level. Now linear is gone, when there is only one member of an mdraid set, there are *no* levels in the liststore, which means selected_level winds up being None.
There are three places I can see in …
=> Guard better against RaidChooser's selected_level being None

plans/tests.fmf
Testing farm sets priority of their repositories to 9 which means the repo is prioritized over all other repositories including our Copr repo with daily builds preventing the latest blivet and libblockdev from being installed.
=> ci: Remove priority from Testing farm repositories

misc/install-test-dependencies.yml
These are aliases, but 'installed' currently doesn't work with dnf5 module.
=> misc: Use 'state: present' instead of 'installed' for packages

blivetgui/dialogs/add_dialog.py, tests/blivetgui_tests/add_dialog_test.py
BIOSBoot cannot be bigger than 2 MiB so we can't allow users to select it when min size limit for the device is bigger than that e.g. on LV where the lower limit is 4 MiB (or twice the PE size).
=> Do not allow selecting formats with that won't fit (#2318274)

blivetgui/blivet_utils.py
In some cases we need the format already configured. This is normally done by applying the action, but we do that later in these cases.
=> Set LUKS format before creating the LUKS device (#2332338)

misc/blivet-gui-tasks.yml
We can just pass a list of packages to the package module, when using "with_items" ansible installs the packages one by one which is significantly slower.
On a system with all dependencies already present.
Before:
real    0m43,513s
user    0m2,916s
sys     0m1,430s
After:
real    0m4,860s
user    0m0,691s
sys     0m0,242s
=> misc: Do not use "with_items" when installing packages

blivetgui/blivet_utils.py, blivetgui/blivetgui.py, blivetgui/dialogs/add_dialog.py, blivetgui/dialogs/size_chooser.py, blivetgui/dialogs/widgets.py, blivetgui/list_devices.py, blivetgui/list_parents.py, blivetgui/list_partitions.py, blivetgui/visualization/logical_view.py, blivetgui/visualization/rectangle.py, tests/blivetgui_tests/add_dialog_test.py, tests/blivetgui_tests/size_widgets_test.py, tests/blivetgui_tests/widgets_test.py, tests/blivetutils_tests/test_10_disks.py
The main reason behind this is to test the blivet support for Stratis which needs to be merged first https://github.com/storaged-project/blivet/pull/915 but this is working (with right versions of blivet and stratisd) and was surprisingly simple to implement.
=> Stratis support

blivetgui/actions_menu.py, blivetgui/actions_toolbar.py, blivetgui/blivet_utils.py, blivetgui/blivetgui.py, blivetgui/dialogs/edit_dialog.py, blivetgui/list_partitions.py, data/ui/blivet-gui.ui, data/ui/rename_dialog.ui, po/blivet-gui.pot, tests/blivetgui_tests/list_partitions_test.py
Marking as draft. The change here should be ok, but we'll need to make some changes in blivet first regarding actions pruning to make this work.
=> Add support for renaming LVM LVs and VGs

tests/pylint/runpylint.py
These constants are still available in blivet. There is a new API but the old API was not removed, see
https://github.com/storaged-project/blivet/pull/1397 for more details.
=> Ignore pylint warnings about blivet.devicefactory.DEVICE_TYPE_*

blivetgui/blivet_utils.py, blivetgui/list_devices.py, po/blivet-gui.pot
In Anaconda MD arrays created directly on top of disks are handled as disks so we should do the same.
Resolves: rhbz#2389105
=> Fix displaying whole-disk MD arrays in installer mode
